### ISSUE TITLE
Create UML for Present and Proposal states

### ISSUE THREAD

**Issue by charan96** [cs361-W16/Group7-2#19]

**Comment by schultsa** [comment]
Have drafts for current and proposal

**Comment by schultsa** [comment]
[current.pdf](https://github.com/cs361-W16/Group7-2/files/135598/current.pdf)
[Proposal.pdf](https://github.com/cs361-W16/Group7-2/files/135599/Proposal.pdf)

Current.pdf contains UML for project at end of assignment 2.
Proposal.pdf contains UML for initial thoughts on implementation.

**Comment by schultsa** [comment]
[proposal.pdf](https://github.com/cs361-W16/Group7-2/files/139037/proposal.pdf)
[current.pdf](https://github.com/cs361-W16/Group7-2/files/139038/current.pdf)

updated.
