### ISSUE TITLE
create UML for final design

### ISSUE THREAD

**Issue by charan96** [cs361-W16/Group7-2#20]

**Comment by schultsa** [comment]
[current.pdf](https://github.com/cs361-W16/Group7-2/files/135586/current.pdf)
[Proposal.pdf](https://github.com/cs361-W16/Group7-2/files/135593/Proposal.pdf)

**Comment by schultsa** [comment]
[implementation.pdf](https://github.com/cs361-W16/Group7-2/files/135595/implementation.pdf)
Current Implementation with Abstract Card Template class

**Comment by schultsa** [comment]
[newImplementation.pdf](https://github.com/cs361-W16/Group7-2/files/139036/newImplementation.pdf)
Updated with what we actually went with.
