### ISSUE TITLE
Display error message in the message box

### ISSUE THREAD

**Issue by charan96** [cs361-W16/Group7-2#8]
Display the error message in the message box when any of the following take place:
- Illegal Move (The destination column of the move function is empty)
- Wrong remove column (The card selected to remove is the highest card)
- Illegal remove (The card is the only one of its suit in the 4 columns; hence cannot be removed)

**Comment by schultsa** [comment]
WE GOT THE TEXT TO SHOW UP IN THE BOX, ****NOTE getElementById  NOT getElementByID
